# Cấu hình Cơ sở dữ liệu SQL Server
db.url=jdbc:sqlserver://localhost:1433;databaseName=QuanLyTraSua;encrypt=true;trustServerCertificate=true;
db.user=sa
db.password=P6t4q29!

# Cấu hình Email gửi OTP
email.user=quang642000@gmail.com
email.password=jhji ifwc qcga ynpw

# Cấu hình SePay API Token
sepay.token=U4RXVN1VBGSWAZR68VQ3SMYHUPFFC6AGOYBKXY8PQBTXAT3YULOBQZI4KDPZ2WSE

# Đường dẫn lưu trữ ảnh (Có thể đổi thành thư mục khác nếu chạy trên Linux/Mac)
upload.dir=C:/tea_pos_images