# Cấu hình Cơ sở dữ liệu SQL Server
db.url=jdbc:sqlserver://localhost:1433;databaseName=QuanLyQuanCafehetcuu1;encrypt=true;trustServerCertificate=true;
db.user=sa
db.password=P6t4q29!

# Cấu hình Email gửi OTP
email.user=${EMAIL_USER:quang642000@gmail.com}
email.password=${EMAIL_PASSWORD:jhji ifwc qcga ynpw}

# Cấu hình SePay API Token
sepay.token=${SEPAY_TOKEN:U4RXVN1VBGSWAZR68VQ3SMYHUPFFC6AGOYBKXY8PQBTXAT3YULOBQZI4KDPZ2WSE}
sepay.bypass=false

# Cấu hình Redis Cache
redis.host=localhost
redis.port=6379

# Thư mục hình ảnh thống nhất
upload.dir=C:/tea_pos_images